import { compare, genSalt, hash } from 'bcrypt';
import Post from './post.js';
import User from './user.js';

let data = {
    users: [
        {
            id: 1,
            username: 'shtag',
            password: '$2b$10$H3UHQURIEqdNaoQgVPaXpuugOFZXNfbCj/4AikUf79a5DO9FuHYkW',
            subscriptions: [3, 2, 11],
            sessions: [
                '$2b$10$NhL.XLXwthdA4kACTPIJg.',
                '$2b$10$iUzRpRZ9pq4pkuRemh09He',
                '$2b$10$874QS9ap6fTcW3c1kNAp6.',
                '$2b$10$.gDhh10s6oAdrj2MwkMdt.',
                '$2b$10$mKIBaD/Wf5AW7g2hblrfM.',
                '$2b$10$T8H2eUTK3.ntOIQm7EvJBe',
            ],
            favorites: [1, 5, 7],
            settings: {
                photo: 'https://i.postimg.cc/pVQbx4hN/profile-img.jpg',
                language: 'en',
                name: 'Vasyl',
                descriptionProfile: 'I am a nice cat!',
            },
        },
        {
            id: 2,
            username: 'shtag2',
            password: '$2b$10$.84C8oCoFv3AE93TQ6yWJOo7fZu1B5.i1lTXeXwveRHL8fd/f0Q.e',
            profilePosts: [],
            subscriptions: [3, 1],
            favorites: [1, 5, 7],
            sessions: ['$2b$10$S.BU8bkwGg5vsZZ5IHIv3e'],
            settings: {
                photo: 'https://i.pinimg.com/564x/50/72/b9/5072b947d36975e9890344aec5757700.jpg',
                language: 'en',
                name: 'shtag2',
                descriptionProfile: '',
            },
        },
        {
            id: 3,
            username: 'shtag3',
            password: '$2b$10$2YHOQJ349flKDZduK.sAJeosEh71YFo/YMdNuuHqIyIDvdTkYqmx2',
            profilePosts: [],
            subscriptions: [1],
            sessions: [],
            favorites: [],
            settings: {
                photo: 'https://i.postimg.cc/6pjZSpW8/base.jpg',
                language: 'en',
                name: 'shtag3',
                descriptionProfile: '',
            },
        },
        {
            id: 4,
            username: 'shtag4',
            password: '$2b$10$fEBddtzr.5kezxDHAHTFRujE6OGcTpBYqgIMmx4WdA/FwJltbJXT2',
            profilePosts: [],
            subscriptions: [1],
            sessions: [],
            favorites: [],
            settings: {
                photo: 'https://i.postimg.cc/6pjZSpW8/base.jpg',
                language: 'en',
                name: 'shtag4',
                descriptionProfile: '',
            },
        },
        {
            id: 5,
            username: 'user1',
            password: '$2b$10$ECNbB3lHCTuqADIVy9m5juG2MCKU8i8TrrY9Lj2Pc8k7LWzE0ayO6',
            profilePosts: [],
            subscriptions: [],
            sessions: [],
            favorites: [],
            settings: {
                photo: 'https://i.postimg.cc/6pjZSpW8/base.jpg',
                language: 'en',
                name: 'user1',
                descriptionProfile: '',
            },
        },
        {
            id: 6,
            username: 'user2',
            password: '$2b$10$qD4SQomOL6dZSm9OMOIV8.BaWjcmpn6gF2ID4ZWSAXo4RPKGb0any',
            profilePosts: [],
            subscriptions: [],
            sessions: [],
            favorites: [],
            settings: {
                photo: 'https://i.postimg.cc/6pjZSpW8/base.jpg',
                language: 'en',
                name: 'user2',
                descriptionProfile: '',
            },
        },
        {
            id: 7,
            username: 'testtest',
            password: '$2b$10$26QXlDLSvq4gsrZlxvx5tesY.EFQ/YIoMv8mTq534ECC/8wVzCSOm',
            profilePosts: [],
            subscriptions: [9],
            sessions: ['$2b$10$IT/mTJ7H/4LKgeKmXhgF1e'],
            favorites: [],
            settings: {
                photo: 'https://i.imgur.com/zNUFi7F.png',
                language: 'en',
                name: 'testtest',
                descriptionProfile: '',
            },
        },
        {
            id: 8,
            username: 'astap13',
            password: '$2b$10$U.LjChJm70KYiO6q2q2FouvRA24XD/ZAop4NOJr8f0ekvkbOZNFz.',
            profilePosts: [],
            subscriptions: [1],
            sessions: ['$2b$10$z26dVFLWsIGVbZoZ/fabku', '$2b$10$vt8MBN7nCBN1flt8l3GMZe'],
            favorites: [38],
            settings: {
                photo: 'https://i.imgur.com/UcrBemq.jpg',
                language: 'en',
                name: 'astap13',
                descriptionProfile: '',
            },
        },
        {
            id: 9,
            username: 'Kristina',
            password: '$2b$10$XVYfubrdamS0qvP5peZciuJ1gtKI6kZWXMT3.Ev6gaXuVSgPz0Yzm',
            profilePosts: [],
            subscriptions: [3, 7],
            sessions: [],
            favorites: [20],
            settings: {
                photo: 'https://i.imgur.com/8ogZ31m.jpg',
                language: 'en',
                name: 'Kristy',
                descriptionProfile: '',
            },
        },
        {
            id: 10,
            username: 'fffffffffsss',
            password: '$2b$10$1lDr5VLorImKqr.6qAGwZem9L0AslUAThGGY.Uhi8UhvOzsxmQNGu',
            profilePosts: [],
            subscriptions: [],
            sessions: [],
            favorites: [],
            settings: {
                photo: 'https://i.postimg.cc/6pjZSpW8/base.jpg',
                language: 'en',
                name: 'fffffffffsss',
                descriptionProfile: '',
            },
        },
        {
            id: 11,
            username: 'asdfzxc',
            password: '$2b$10$Cy0Krj2LR0jn8un/Kppc5.lIF5No/4ljVN2jQJYZlFYSrrn1SEP.W',
            profilePosts: [],
            subscriptions: [],
            sessions: ['$2b$10$J/CKYG7PD9yhNzkWBur67u'],
            favorites: [18],
            settings: {
                photo: 'https://i.postimg.cc/6pjZSpW8/base.jpg',
                language: 'en',
                name: 'asdfzxc',
                descriptionProfile: '',
            },
        },
        {
            id: 12,
            username: 'Yauhen',
            password: '$2b$10$YM/qDyJPj9rID2xzFV0Jle9CD9eySjmgAklYxTxwbFK.cjzH7sn8q',
            profilePosts: [],
            subscriptions: [],
            sessions: ['$2b$10$kejqilaNtEtQykice8pvze', '$2b$10$2/Iu2eOVTXMBbT2CU6RKM.'],
            favorites: [21],
            settings: {
                photo: 'https://i.postimg.cc/6pjZSpW8/base.jpg',
                language: 'en',
                name: 'Yauhen',
                descriptionProfile: 'testing',
            },
        },
    ],
    posts: [
        {
            id: 1,
            image: 'https://i.postimg.cc/90sJyWzX/old-home.jpg',
            description: 'Here is my old apartment',
            date: 1000167089287,
            likes: [],
            comments: [],
            author: 1,
        },
        {
            id: 2,
            image: 'https://i.postimg.cc/C11NtZqL/traveler.jpg',
            description: "It's me on a train, I like traveling...",
            date: 1235967689287,
            likes: [],
            comments: [],
            author: 1,
        },
        {
            id: 3,
            image: 'https://i.postimg.cc/vmXh37DN/sleep.jpg',
            description: 'Was working and fell asleap',
            date: 1345967689287,
            likes: [],
            comments: [],
            author: 1,
        },
        {
            id: 4,
            image: 'https://i.postimg.cc/BZzhrCNW/playful-mood.jpg',
            description: 'Have some playful mood',
            date: 1432967689287,
            likes: [],
            comments: [],
            author: 1,
        },
        {
            id: 5,
            image: 'https://i.postimg.cc/Mp7djJwx/photo-2023-02-09-20-23-42.jpg',
            description: 'Bring my human for a little walk',
            date: 1543967689287,
            likes: [],
            comments: [],
            author: 1,
        },
        {
            id: 6,
            image: 'https://i.postimg.cc/CxTc1LWm/My-buds.jpg',
            description: 'Invite buds for a meal',
            date: 1567967689287,
            likes: [8],
            comments: [],
            author: 1,
        },
        {
            id: 7,
            image: 'https://i.postimg.cc/7h5KCCHQ/meet-some-gangsters.jpg',
            description: 'Meet dangerous gangsters..',
            date: 1598967689287,
            likes: [],
            comments: [],
            author: 1,
        },
        {
            id: 8,
            image: 'https://i.postimg.cc/9M8xFPh7/bright-future.jpg',
            description: 'Looking in bright future',
            date: 1623967689287,
            likes: [],
            comments: [],
            author: 1,
        },
        {
            id: 9,
            image: 'https://i.postimg.cc/VLb7mbHJ/i-was-sleeps-now-im-not.jpg',
            description: 'I was sleeping, now I am not',
            date: 1646967689287,
            likes: [],
            comments: [],
            author: 1,
        },
        {
            id: 10,
            image: 'https://i.postimg.cc/GpbzFg3D/chick.jpg',
            description: 'Look at this chick',
            date: 1675967689288,
            likes: [],
            comments: [],
            author: 1,
        },
        {
            id: 11,
            image: 'https://images.unsplash.com/photo-1571988840298-3b5301d5109b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
            description: "It's my 1 photo",
            date: 1677549212984,
            likes: [],
            comments: [],
            author: 2,
        },
        {
            id: 12,
            image: 'https://images.unsplash.com/photo-1608848461950-0fe51dfc41cb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80',
            description: "It's my 2 photo",
            date: 1677549212984,
            likes: [],
            comments: [],
            author: 2,
        },
        {
            id: 13,
            image: 'https://images.unsplash.com/photo-1579168765467-3b235f938439?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80',
            description: "It's my 3 photo",
            date: 1677549212984,
            likes: [],
            comments: [],
            author: 2,
        },
        {
            id: 14,
            image: 'https://images.unsplash.com/photo-1586289883499-f11d28aaf52f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
            description: "It's my 4 photo",
            date: 1677549212984,
            likes: [],
            comments: [],
            author: 2,
        },
        {
            id: 15,
            image: 'https://images.unsplash.com/photo-1601373879104-b4290a56b691?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=670&q=80',
            description: "It's my 5 photo",
            date: 1677549212984,
            likes: [],
            comments: [],
            author: 2,
        },
        {
            id: 16,
            image: 'https://images.unsplash.com/photo-1597626133663-53df9633b799?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
            description: "It's my 1 photo",
            date: 1677549213186,
            likes: [],
            comments: [],
            author: 3,
        },
        {
            id: 17,
            image: 'https://images.unsplash.com/photo-1567270671170-fdc10a5bf831?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
            description: "It's my 2 photo",
            date: 1677549213186,
            likes: [],
            comments: [{ text: 'test', date: 1677605654929, likes: [1], id: 1, author: 1 }],
            author: 3,
        },
        {
            id: 18,
            image: 'https://images.unsplash.com/photo-1605450648855-63f9161b7ef7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
            description: "It's my 3 photo",
            date: 1677549213186,
            likes: [11],
            comments: [
                { text: 'dasdasd', date: 1677604433593, likes: [11], id: 1, author: 11 },
                { text: 'xzzxczx', date: 1677604446815, likes: [], id: 2, author: 11 },
            ],
            author: 3,
        },
        {
            id: 19,
            image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=644&q=80',
            description: "It's my 4 photo",
            date: 1677549213186,
            likes: [],
            comments: [],
            author: 3,
        },
        {
            id: 20,
            image: 'https://images.unsplash.com/photo-1572171572779-e93ec53b8024?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80',
            description: "It's my 5 photo",
            date: 1677549213187,
            likes: [],
            comments: [
                { text: 'fdsfsdfsdfsd', date: 1677602659939, likes: [9, 12], id: 1, author: 7 },
                { text: 'Myw!', date: 1677606618972, likes: [12], id: 2, author: 9 },
                { text: 'Kristina, hello', date: 1677607088005, likes: [], id: 3, author: 12 },
            ],
            author: 3,
        },
        {
            id: 21,
            image: 'https://i.imgur.com/XwC2HoV.jpg',
            description: '#404',
            date: 1677604340403,
            likes: [12],
            comments: [
                { text: 'test comment', date: 1677609326673, likes: [], id: 1, author: 12 },
                { text: 'test comment', date: 1677609332862, likes: [], id: 2, author: 12 },
                { text: 'test comment', date: 1677609333391, likes: [], id: 3, author: 12 },
                { text: 'test failed', date: 1677609451151, likes: [], id: 4, author: 12 },
                { text: 'test failed', date: 1677609510211, likes: [], id: 5, author: 12 },
            ],
            author: 9,
        },
        {
            id: 22,
            image: 'https://i.imgur.com/wWUBZCv.gif',
            description: 'рпрпарпа',
            date: 1677605237078,
            likes: [],
            comments: [],
            author: 7,
        },
        {
            id: 24,
            image: 'https://i.imgur.com/jtXYuFY.jpg',
            description: '#picture',
            date: 1677609109718,
            likes: [],
            comments: [],
            author: 12,
        },
        {
            id: 28,
            image: 'https://i.imgur.com/jtXYuFY.jpg',
            description: '#picture',
            date: 1677609110178,
            likes: [],
            comments: [],
            author: 12,
        },
        {
            id: 29,
            image: 'https://i.imgur.com/jtXYuFY.jpg',
            description: '#picture',
            date: 1677609110453,
            likes: [],
            comments: [],
            author: 12,
        },
        {
            id: 31,
            image: 'https://i.imgur.com/jtXYuFY.jpg',
            description: '#picture',
            date: 1677609110719,
            likes: [],
            comments: [],
            author: 12,
        },
        {
            id: 33,
            image: 'https://i.imgur.com/jtXYuFY.jpg',
            description: '#picture',
            date: 1677609111120,
            likes: [],
            comments: [],
            author: 12,
        },
        {
            id: 34,
            image: 'https://i.imgur.com/jtXYuFY.jpg',
            description: '#picture',
            date: 1677609111270,
            likes: [],
            comments: [],
            author: 12,
        },
        {
            id: 35,
            image: 'https://i.imgur.com/PVkpfMg.jpg',
            description: '',
            date: 1677612102897,
            likes: [8],
            comments: [],
            author: 8,
        },
        {
            id: 36,
            image: 'https://i.imgur.com/9dyDlXf.jpg',
            description: '',
            date: 1677612119464,
            likes: [8],
            comments: [
                { text: 'test', date: 1677612279094, likes: [], id: 1, author: 8 },
                { text: 'test', date: 1677612295072, likes: [], id: 2, author: 8 },
            ],
            author: 8,
        },
        {
            id: 37,
            image: 'https://i.imgur.com/nLH4V1v.jpg',
            description: '',
            date: 1677612149205,
            likes: [8],
            comments: [{ text: 'test', date: 1677613657419, likes: [], id: 1, author: 8 }],
            author: 8,
        },
        {
            id: 38,
            image: 'https://i.imgur.com/TZMt45i.jpg',
            description: 'Cute one',
            date: 1677614412966,
            likes: [],
            comments: [],
            author: 1,
        },
    ],
};

export default data;
